### ISSUE TITLE
There's 0 releases for this project.

### ISSUE THREAD

**Issue by audiogamer22** [stormdragon2976/tintin-stickmud#1]
Hi, I'd like to play stickmud and am blind so click on their link to download the soundpack but you don't seamed to have released it in a way I can download.

Is it still being worked on and if not, is there a soundpack that is?

**Comment by lilmike** [comment]
Hiya,
Yes, it is still being worked on. The way this project is done we don't
do releases -- whatever gets pushed to master is what is released, so
you need to either run "git clone
https://github.com/stormdragon2976/tintin-stuickmud.git" or there is a
way to download a .zip or .tar.gz of the master branch. I would highly
recommend the git clone method, as if you do it this way you can simply
run "git pull" to get the latest changes, but it's certainly possible to
download the project without any releases.
-Michael.





-- 
Sorry about the test, it's just a me thing.
Michael Taboada, Creator of Games. Does that make me a god, well, sorta.
My pgp key: 79BC390E8864CD71305D4DD606CD2197A6EE5ED7
My website: https://michaels.world
2MB website: https://2mb.games
Don't believe everything you read on the internet. I might not be real, you might not be real, and this email certainly isn't real.
Sent from my smart home...
stationary bicycle

**Comment by audiogamer22** [comment]
Hi Michael, I’m new to using GitHub in this way, could you walk me through the cloning method please, thanks.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by lilmike** [comment]
It would help to know what OS you're on, then I can possibly give you
more exact instructions. As a side note, this really only works well on
mac and linux, wintin++ just doesn't have the support we need for it.
-Michael.





-- 
Sorry about the test, it's just a me thing.
Michael Taboada, Creator of Games. Does that make me a god, well, sorta.
My pgp key: 79BC390E8864CD71305D4DD606CD2197A6EE5ED7
My website: https://michaels.world
2MB website: https://2mb.games
Don't believe everything you read on the internet. I might not be real, you might not be real, and this email certainly isn't real.
Sent from my musically gifted...
stationary bicycle

**Comment by audiogamer22** [comment]
Ah, I’m on windows. Do you know any other sound packs for the mud?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by lilmike** [comment]
Hiya,
Unfortunately I don't. The stickmud official script set is written in
mudlet, which is not fully accessible yet, but I think progress is being
made in that direction, so maybe you could use that some time in the
future. The only other option for our pack to work on windows would be
to use wsl and do a very complicated proceedure to connect sound in the
wsl linux to sound on the windows side, though I haven't messed with
that in a long time, so maybe it has improved. Maybe Billy can help with
that, but then again maybe not @stormdragon2976
-Michael.






-- 
Sorry about the test, it's just a me thing.
Michael Taboada, Creator of Games. Does that make me a god, well, sorta.
My pgp key: 79BC390E8864CD71305D4DD606CD2197A6EE5ED7
My website: https://michaels.world
2MB website: https://2mb.games
Don't believe everything you read on the internet. I might not be real, you might not be real, and this email certainly isn't real.
Sent from my supernatural...
stationary bicycle

**Comment by audiogamer22** [comment]
Hey, that’s completely fine.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
